### ISSUE TITLE
请求移除vs生成的非代码文件

### ISSUE THREAD

**Issue by mercury233** [Lucky-Koishi/KoishiEx#1]
vs在运行和编译过程中会生成大量的临时文件，这些文件不需要包含在源代码里，而且会大大增加库的体积，使其难以克隆

因此请求使用git的gitignore功能移除他们，并建议参考 https://help.github.com/articles/removing-sensitive-data-from-a-repository/ 清理commit历史中的文件

**Comment by Lucky-Koishi** [comment]
我也是刚上手github，我会及时清理临时文件。
