### ISSUE TITLE
VS2015无法编译

### ISSUE THREAD

**Issue by mercury233** [Lucky-Koishi/KoishiEx#2]
![image](https://user-images.githubusercontent.com/13391795/32114276-a244f950-bb75-11e7-8789-15bc34b50c73.png)
升级之后

```
1>f:\works\koishiex\koishiex\sha256.cpp(30): error C2872: “uint32_t”: 不明确的符号
1>  c:\program files (x86)\microsoft visual studio 14.0\vc\include\stdint.h(23): note: 可能是“unsigned int uint32_t”
1>  f:\works\koishiex\koishiex\sha256.h(7): note: 或  “KoishiSHA256::uint32_t”
```

此外
![image](https://user-images.githubusercontent.com/13391795/32114345-def50f16-bb75-11e7-9da8-e0254a469223.png)
![image](https://user-images.githubusercontent.com/13391795/32114367-ed91e51c-bb75-11e7-979a-4ea14a7bb0ef.png)
DemoEx是不是还没更新

**Comment by mercury233** [comment]
打开ExRabbit.vcxproj的话是这样
> 1>LINK : fatal error C1047: 对象或库文件“libpng15.lib”是使用比创建其他对象所用编译器旧的编译器创建的；请重新生成旧的对象和库

**Comment by Lucky-Koishi** [comment]
已经更新了，目前应该不会报错了。
因为在此之前系统地对IMGobject类进行一次优化。
至于libpng15.lib，可能你需要重新下载并使用VS2015进行编译……因为我没有用过VS2015对版本转换也不是很了解，可能帮不了你太多，http://www.libpng.org/pub/png/libpng.html LIBPNG下载地址

**Comment by No5972** [comment]
mark... (with VS2015)
