### ISSUE TITLE
Hidpi界面问题

### ISSUE THREAD

**Issue by LarkinZero** [Lucky-Koishi/KoishiEx#3]
Windows 10 1709
OS内部版本：16299.19
![sp171028_200045](https://user-images.githubusercontent.com/6387162/32134216-f4b40ed8-bc1a-11e7-9699-3447c5a0db8d.png)

**Comment by Lucky-Koishi** [comment]
抱歉，因为PIC和CLR列表以及图像绘制是写死的，所以分辨率和系统字体调整会影响这些控件的正常位置。
尝试修改下CExRabbit.cpp内switchIMGver（249行）函数下各界面的参数以适应你的窗口；
颜色浏览区域左上角坐标在（639行）；
绘制界面左上角坐标在（1001行）。
